# Generated by Django 5.2.1 on 2025-07-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='status',
        ),
    ]
