# Generated by Django 5.2.1 on 2025-08-26 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_post_image_alter_post_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='social_network.post')),
                ('post_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post_follower', 'post')},
            },
        ),
    ]
