# Generated by Django 5.2.1 on 2025-09-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Diss_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post2', to='social_network.post')),
                ('post_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_follower2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post_follower', 'post')},
            },
        ),
    ]
