# Generated by Django 5.2.1 on 2025-09-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_alter_comment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community_avatar/')),
                ('title', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('permission', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
