# Generated by Django 5.2.1 on 2025-10-28 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0013_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diskussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diskussion', to='social_network.community')),
                ('diskussion_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diskussion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
