# Generated by Django 5.2.1 on 2025-11-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0014_diskussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskussion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='social_network.diskussion'),
        ),
    ]
